name: survival
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - python
  - scipy
  - seaborn
  - tslearn
  - tqdm
  - lifelines
